export const COMMON_REQUEST_DATA_BEGIN = 'COMMON_REQUEST_DATA_BEGIN';
export const COMMON_REQUEST_DATA_SUCCESS = 'COMMON_REQUEST_DATA_SUCCESS';
export const COMMON_REQUEST_DATA_FAILURE = 'COMMON_REQUEST_DATA_FAILURE';
export const COMMON_REQUEST_DATA_DISMISS_ERROR = 'COMMON_REQUEST_DATA_DISMISS_ERROR';
export const COMMON_SET_LOADING = 'COMMON_SET_LOADING';
